# config/validator/validation.yaml
App\Entity\Book:
    properties:
        title:
            - NotBlank: ~
            - Length:
                min: 3
                max: 250
                minMessage: 'The title must be at least {{ limit }} char long'
                maxMessage: 'The title must be longer than {{ limit }} char'
                allowEmptyString: false